# Generated by Django 5.0.6 on 2024-05-27 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "email",
                    models.EmailField(
                        max_length=100, unique=True, verbose_name="Электронная почта"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="не обязательное поле",
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Завершена", "Завершена"),
                            ("Создана", "Создана"),
                            ("Запущена", "Запущена"),
                        ],
                        default="Создана",
                        max_length=150,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("Каждые пять минут", "Каждые пять минут"),
                            ("Раз в день", "Раз в день"),
                            ("Раз в неделю", "Раз в неделю"),
                            ("Раз в месяц", "Раз в месяц"),
                        ],
                        default="Раз в день",
                        max_length=150,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="(формат 11.05.2024) не обязательное поле",
                        null=True,
                        verbose_name="Дата начала",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="не обязательное поле",
                        null=True,
                        verbose_name="Дата окончания",
                    ),
                ),
                (
                    "clients",
                    models.ManyToManyField(
                        to="mailing.client", verbose_name="Клиенты для рассылки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время попытки отправки"
                    ),
                ),
                ("status", models.BooleanField(verbose_name="Статус попытки отправки")),
                (
                    "server_response",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Ответ сервера почтового сервиса",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог рассылки",
                "verbose_name_plural": "Логи рассылок",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Тема")),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
