# Generated by Django 5.0.6 on 2024-06-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="clients",
            field=models.ManyToManyField(
                related_name="mailing",
                to="mailing.client",
                verbose_name="Клиенты для рассылки",
            ),
        ),
    ]
