# Generated by Django 4.2.2 on 2024-06-22 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_mailing_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ("name",),
                "permissions": [
                    ("deactivate_mailing", "Can deactivate mailing"),
                    ("view_all_mailings", "Can view all mailings"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
