# Generated by Django 4.2.2 on 2024-07-01 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0006_remove_message_mailing_mailing_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="log",
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
            },
        ),
    ]
