# Generated by Django 4.2.2 on 2024-07-01 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0007_alter_log_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="log",
            name="client",
        ),
    ]
