# Generated by Django 4.2.2 on 2024-07-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0008_remove_log_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="status",
            field=models.CharField(
                choices=[("successful", "успешно"), ("failed", "неуспешно")],
                max_length=50,
                verbose_name="Cтатус рассылки",
            ),
        ),
    ]
