# Generated by Django 4.2.2 on 2024-07-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0009_alter_log_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="status",
            field=models.CharField(
                choices=[("Успешно", "Успешно"), ("Неуспешно", "Неуспешно")],
                max_length=50,
                verbose_name="Cтатус рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("Раз в день", "Раз в день"),
                    ("Раз в неделю", "Раз в неделю"),
                    ("Раз в месяц", "Раз в месяц"),
                ],
                default="Раз в день",
                max_length=150,
                verbose_name="Периодичность",
            ),
        ),
    ]
