# Generated by Django 4.2.2 on 2024-07-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0010_alter_log_status_alter_mailing_periodicity"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="next_send_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время следующей отправки"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=100, verbose_name="Электронная почта"),
        ),
    ]
